import 'jquery/dist/jquery'
import 'popper.js/dist/popper'
import 'bootstrap/dist/js/bootstrap'
import 'jquery.easing/jquery.easing'
import './sb-admin-2'
import 'chart.js/dist/Chart'
import './chart-area-demo'
import './chart-pie-demo'
